### ISSUE TITLE
Help with using the tool

### ISSUE THREAD

**Issue by js1972** [bkrencker/HDIBackupRestore#3]
Hello and thankyou for a wonderful project. Honestly - why is this not standard in the hana cloud tooling. ;-) 

I've managed to install the app on BTP - had to make a few minor modifications  due to windows specific slashes and also remove the xsappname from the mta.yaml as its already in the xs-security.json and the mta.yaml version of xsappname suffixed the org name which is problematic since a lot of org names have ` ` and `-` which the deployer doesn't seem to like.

My question though is - how do I use this app?

- When I start it there is an empty list report of applications. Am I supposed to create those applications?
- When I create an application there is then an empty list of hdi containers - am I supposed to create those? I was under the impression that the app would "see" the hdi containers on the connected db?
- When creating a container - is this simply a reference to the container that already exists in hana cloud or will this literally create a new hdi container

I guess you could sum this up as - is the app supposed to enable me to manage the containers for existing applications or do you have to use this app to first create the container - and then build your apps and point them to the containers created by this app?

**Comment by js1972** [comment]
ok looking at the code I see there is no capability to create a hdi container. So it must be that as a user - creating applications is just a name/reference and nothing to do with the db on BTP.
And I need to "create" a HDI container which is not actually creating one but instead just referencing an existing container. Once this is done the options for backup and restore are made available.
So I think I've answered my questions here - please correct me if I am wring though.  ;-)
Would be good to have a value help on the container so we dont have to to the painful task of finding the container id.  ;- )

**Comment by js1972** [comment]
In fact - how do you even get teh guid for an existing hdi container? I have deployed a CAP app the the hdi container is seen as `btprc-dev` - I can't see anyhere in the hana tooling where it shows the guid for this.

**Comment by js1972** [comment]
Hi @bkrencker . I managed to add a row (app, hdi container). The container id from the app binding had to be changed to use upper case letters and no `-` chars and after that it saved. But upon clicking the backup button it says the container does not exist.

I used the instance guid from the VCAP_SERVICES:
<img width="517" alt="image" src="https://github.com/bkrencker/HDIBackupRestore/assets/1317161/764dd985-bd77-4324-b817-1646dd71071d">

Is that the right value to use?

The actual error is:
<img width="592" alt="image" src="https://github.com/bkrencker/HDIBackupRestore/assets/1317161/6f5d4571-15d8-40c5-b7f2-26dcaabf07d0">

I'm thinking the instance is just the cloud foundry instance for the hdi service and not the actual container id. Maybe the container id should be the schema - but in this case the schema name is `BTPRESOURCECONSUMPTION_DEV` so I can't enter that as the hdi guid either.

**Comment by js1972** [comment]
Maybe there is a way to see all the container guids and names from an sql console? Not sure why the hdi administration app in hana cloud can't show you this.

**Comment by bkrencker** [comment]
The HDI Container ID (which is the DB SCHEMA name) is found here in the VCAP Binding:

![image](https://github.com/bkrencker/HDIBackupRestore/assets/54358901/21689895-6d26-4329-a662-601635225871)

**Comment by js1972** [comment]
That wont work in the app when the SCHEMA is as shown here - it only allows a guid:
<img width="356" alt="image" src="https://github.com/bkrencker/HDIBackupRestore/assets/1317161/980dc85e-8142-4fda-bc13-3dba289c9933">

**Comment by js1972** [comment]
@bkrencker you can see here that the app (which I want to manage its hdi container) is set to use a specific name for the schema and not a generated guid:
<img width="379" alt="image" src="https://github.com/bkrencker/HDIBackupRestore/assets/1317161/9f2a9a30-0dab-41cf-855a-1f1042b74638">

I guess this means that this app can't handle this type of hdi container?

**Comment by bkrencker** [comment]
Ahh OK you provide a name there. Thats not a problem, you just need to remove the regex here: https://github.com/bkrencker/HDIBackupRestore/blob/0d4620822ef3e0aca600f4f23113a9a73e956207/db/schema.cds#L12

Then you can add the hdi container with this name.

**Comment by js1972** [comment]
Ok. Maybe I’ll find a way to handle both and send in a pr. ;-)

**Comment by js1972** [comment]
Hi @bkrencker  since the container id is really the schema name (which can be pretty much any string) I've just removed the validation as spoken about above. I don't think there are any checks I can put in there. I also changed some of the text labels from "container guid" to "container (schema name)". I could calidate the schema name
I removed the xsappname from the mta because its already in the xs-security.json and having it in the mta with an {org} variable is problematic for a lot of org names (especially if you keep the default the btp gives you when you enable cf on a subaccount).
Last thing I did was replace the double backslash `\\` you had in the package.json scripts for deploy - with a single forward slash which is usually what is used. Did you have an issue with this on a windows computer?

Not sure if you want these changes - if you do I'll send a PR. Other than that the app works great now. Love it.

Also a cool new feature would be to enable the user to set the database from within the app instead of via environment variables. Could have a simply Settings entity for it - for example and a fiori element page action to set the values.

**Comment by bkrencker** [comment]
Hi @js1972 that sounds great, I am happy that everything worked out. Yes please send a PR 👍

I will be on vacation but try to find some time to merge everything. I also started a discussion with Feature Requests.

Concerning the DB credentials in env variables, the reason why I don't put them into a db table are security concerns. Access to env variable needs BTP Platform Authorization, whereas the App itself could be public or otherwise accesible. But yeah, for user experience it would definitely be better to have them in the app I agree. 

Best regards,
Ben

**Comment by js1972** [comment]
Great reason not to include the db info in the app.  ;-)
